### ISSUE TITLE
Disable hyperlink from brackets

### ISSUE THREAD

**Issue by amir-zeldes** [cligu/gitdox#53]
Cells containing paired square brackets should not be rendered as hyperlinks in EtherCalc

**Comment by ctschroeder** [comment]
This is appearing a lot in the Coptic SCRIPTORIUM corpora.  Is it a problem for export into our various data formats?

**Comment by amir-zeldes** [comment]
No, it's a pure visualization issue, it won't affect export. The problem causing them to appear has also been fixed already for future imports, but has not been applied retroactively to corpora already in the system. Since it has no effect I haven't been focusing on it.

**Comment by ctschroeder** [comment]
Thank you!

**Comment by amir-zeldes** [comment]
Fixed in 40523f2b472d9e835997740edc0e0d727977db81

**Comment by ctschroeder** [comment]
This is listed as fixed but I'm still seeing it appear in the Johannes Canons docs

**Comment by amir-zeldes** [comment]
Are you seeing this in input coming back from the Coptic NLP API, or by manually typing brackets? I can reproduce the latter, but not the former (so if I have brackets in XML and hit Tabulate, they are preserved in the output in Ether mode)
